num1=int(input("enter a number here: "))
num2=int(input("enter a number here: "))
num3=int(input("enter a number here: "))
num4=int(input("enter a number here: "))
num5=int(input("enter a number here: "))
print(num1-num2)
print(num3+num5)
print(num4*num2)
print(num3/num1)
print(num1%num5)
print(num2//num3)